# Generated by Django 4.1 on 2022-10-08 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_name", models.CharField(max_length=20)),
                (
                    "platform_link",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "platform_img",
                    models.ImageField(default="", upload_to="notifier/images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyContest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selectedContest",
                    models.ManyToManyField(blank=True, to="Notifier.platform"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contest", models.CharField(max_length=50)),
                ("contest_link", models.CharField(max_length=200)),
                ("when", models.DateTimeField()),
                ("duration", models.IntegerField(default=3)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Notifier.platform",
                    ),
                ),
            ],
        ),
    ]
