# Generated by Django 4.1 on 2022-08-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_img', models.ImageField(upload_to='images/')),
                ('platform', models.CharField(max_length=20)),
                ('contest', models.CharField(max_length=50)),
                ('contet_link', models.CharField(max_length=200)),
                ('when', models.DateTimeField()),
                ('duration', models.IntegerField(default=3)),
            ],
        ),
    ]
