# Generated by Django 4.1 on 2022-10-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notifier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="duration",
            field=models.CharField(max_length=20),
        ),
    ]
