# Generated by Django 4.1 on 2022-08-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='contet_link',
            new_name='contest_link',
        ),
    ]
