# Generated by Django 4.1 on 2022-08-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifier', '0002_rename_contet_link_contest_contest_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='platform_img',
            field=models.ImageField(default='', upload_to='notifier/images/'),
        ),
    ]
