# Generated by Django 4.1 on 2022-08-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifier', '0003_alter_contest_platform_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='platform_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
