# Generated by Django 4.1 on 2022-08-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifier', '0005_alter_contest_platform_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='platform_img',
            field=models.ImageField(default='', upload_to='notifier/images/'),
        ),
    ]
