# Generated by Django 4.1 on 2022-09-17 10:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Notifier", "0007_mycontests"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MyContests",
            new_name="MyContest",
        ),
    ]
