# Generated by Django 4.1 on 2022-09-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notifier", "0008_rename_mycontests_mycontest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mycontest",
            name="selectedContest",
        ),
        migrations.AddField(
            model_name="mycontest",
            name="selectedContest",
            field=models.ManyToManyField(to="Notifier.contest"),
        ),
    ]
