# Generated by Django 4.1 on 2022-09-17 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Notifier", "0009_remove_mycontest_selectedcontest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mycontest",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
