# Generated by Django 4.1 on 2022-09-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notifier", "0012_remove_mycontest_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contest",
            old_name="platform",
            new_name="platform_name",
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_name", models.CharField(max_length=20)),
                ("platform_link", models.CharField(default="", max_length=200)),
                ("contest", models.ManyToManyField(to="Notifier.contest")),
            ],
        ),
    ]
