# Generated by Django 4.1 on 2022-09-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Notifier", "0013_rename_platform_contest_platform_name_platform"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mycontest",
            name="selectedContest",
        ),
    ]
