# Generated by Django 4.1 on 2022-09-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notifier", "0014_remove_mycontest_selectedcontest"),
    ]

    operations = [
        migrations.AddField(
            model_name="mycontest",
            name="selectedContest",
            field=models.ManyToManyField(to="Notifier.platform"),
        ),
    ]
