# Generated by Django 4.1 on 2022-09-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notifier", "0015_mycontest_selectedcontest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mycontest",
            name="selectedContest",
            field=models.ManyToManyField(null=True, to="Notifier.platform"),
        ),
    ]
