# Generated by Django 4.1 on 2022-09-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notifier", "0017_alter_mycontest_selectedcontest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platform",
            name="contest",
            field=models.ManyToManyField(blank=True, to="Notifier.contest"),
        ),
    ]
